### PR TITLE
SMTP: Use mailAccount to link to IMAP/POP3 account - fixes #155

### LINKED ISSUE #155: Dependent/main accounts
### Situation
When the user sets up an Office365, or Google, or Mustang account, the mail account also comes with address book sync, calendar sync, file sharing, and video conference. We are creating corresponding "accounts" in Mustang, one for each address book, one for each calendar etc.

### Problem

Their login is directly dependent on the login of the main mail account. I.e. if I didn't log in to the mail account, then saving a contact to the server will fail.

#### Link

Create an explicit "dependent" and "main" account link. I.e. the address book has a "mainAccount" property which points to the mail account. And the mail account has a "dependentAccounts" array, which points to the address books, calendars, file sharing, video conference accounts.

#### isLoggedIn
The address book's `isLoggedIn` will simply return `this.mainAccount.isLoggedIn`. For that to work, the address book needs to subscribe to the main account changes on load (in the moment when the `mainAccount` property is set), so that listeners to the address book `isLoggedIn` state are updated as soon as the mail account login state changes.

#### Login
Likewise, the address book's `login()` function will simply delegate to `this.mainAccount.login()`.

When a contact needs to be saved to the server, and the main account is not logged in, the dependent account needs to trigger the login. Whether an interactive login is requested depends on whether the user himself started the modification directly, or whether it's a background process.

#### Save link on disk

The link needs to be saved on disk, and restored on load.

### PR DESCRIPTION
**Pull request by benbucksch**
Part of #155. Followup to #573.

### CODE REVIEW

File: app/logic/Mail/ActiveSync/ActiveSyncAccount.ts [hunk 1]
```diff
@@ -441,15 +441,15 @@ export class ActiveSyncAccount extends MailAccount {
             break;
           case FolderType.Calendar:
           case FolderType.UserCalendar:
-            // TODO compare calendar ID
-            let calendar = appGlobal.calendars.find((calendar: ActiveSyncCalendar) => calendar.mainAccount == this) as ActiveSyncCalendar | null;
+            let calendar = appGlobal.calendars.find(calendar => calendar.mainAccount == this && calendar.url == url.toString()) as ActiveSyncCalendar | null;
```
Comment (NeilRashbrook) [inline app/logic/Mail/ActiveSync/ActiveSyncAccount.ts:444]: Aha, I had been wondering about this!

Comment (benbucksch) [reply app/logic/Mail/ActiveSync/ActiveSyncAccount.ts:444]: Yes, putting the serverID into the URL was mighty subtle!

We should put it into a separate field. It wasn't possible before, but now with the JSON properties, we can store arbitrary data for each account.

Comment (benbucksch) [reply app/logic/Mail/ActiveSync/ActiveSyncAccount.ts:444]: Thanks for having noticed this. This is the level of review that I needed.

**Comment by benbucksch** [comment]
@NeilRashbrook Please review

File: app/logic/Mail/AutoConfig/manualConfig.ts [hunk 2]
```diff
@@ -16,7 +16,7 @@ export function makeManualConfig(emailAddress: string, password: string): MailAc
   config.authMethod = AuthMethod.Password;
   config.source = "manual";
 
-  let outgoing = new SMTPAccount();
+  let outgoing = newAccountForProtocol("smtp") as any as SMTPAccount;
```
Comment (NeilRashbrook) [inline app/logic/Mail/AutoConfig/manualConfig.ts:19]: Was account setup broken because it wasn't saving the account or something? (I'm worried that these changes relate to the "FOREIGN KEY constraint failed" errors I was seeing.)

(The `as any` shouldn't be necessary, but I've had similar problems before, so I'll take your word for it.)

File: app/logic/Mail/SQL/SQLMailAccount.ts [hunk 3]
```diff
@@ -85,13 +79,10 @@ export class SQLMailAccount {
...
-    for (let account of accounts) {
-      let id = account.outgoingAccountID;
-      delete account.outgoingAccountID;
-      if (id) {
-        account.outgoing = smtpAccounts.find(acc => acc.id == id);
-      }
+    // Need to special-case it here, because SMTP accounts
+    // aren't in `appGlobal.emailAccounts`, so `setMainAccounts()` won't find them.
+    for (let smtp of smtpAccounts) {
+      smtp.mainAccount = accounts.find(acc => acc.id == smtp._mainAccountID);
```
Comment (NeilRashbrook) [inline app/logic/Mail/SQL/SQLMailAccount.ts:85]: (I was wondering how this worked with other cases, but I think what happens is that this causes the account to be the outgoing account of its main account, at which point it will start appearing in `allAccounts()`.)

**Review by NeilRashbrook — COMMENTED** [review]
I had originally set up an EWS account using a previous version of this patch (commit 3c5aa46), which continued to work, however for rest of the review I used master (commit 844ab27).

When I tried to create an OWA account I got "FOREIGN KEY constraint failed". After cancelling setup I noticed that the calendar and addressbook had already been added, although the mail account had not actually been saved at this point.

(I was also confused by there being two logins, one using the EWS/ActiveSync webview, one using the OWA popup.)

I was then able to create an ActiveSync account, which seemed to be working normally, e.g. all of the calendars were discovered as expected.

I then tried to create an IMAP account and also a second EWS account but each time I also got "FOREIGN KEY constraint failed". In the case of the EWS account a phantom address book had been created (I couldn't delete it but it went away after I restarted).

I was then able to create a second ActiveSync account, which also seemed to be working normally.

File: app/logic/Mail/MailAccount.ts [hunk 4]
```diff
@@ -118,13 +115,16 @@ export class MailAccount extends TCPAccount {
   }
 
   async save(): Promise<void> {
+    if (this.outgoing) {
+      this.outgoing.mainAccount = this;
+    }
+    console.log("mail account save", this.protocol, this.name, this, "outgoing", this.outgoing, "mainaccount", this.mainAccount, "storage", this.storage);
+    await super.save();
     await this.storage?.saveAccount(this);
```
Comment (NeilRashbrook) [inline app/logic/Mail/MailAccount.ts:123]: The problem here is that `super.save` tries to save all dependent accounts, which doesn't work until this account has been saved. This causes the creation of IMAP and POP3 accounts to fail, because they try to save the SMTP account first.

**Review by NeilRashbrook — COMMENTED** [review]
I've since found that ActiveSync works because it has a custom `verifyLogin` which doesn't try to create and save any dependent accounts, but EWS and OWA fail because `verifyLogin` just defaults to calling `login(true);` which tries to create dependent addressbook and calendar accounts, and this fails because the main account hasn't been saved yet. (Presumably under the old code, these accounts would simply be saved, and would linger if you cancelled account setup at the last second.)

**Comment by benbucksch** [comment]
> I've since found that ActiveSync works because it has a custom `verifyLogin` which doesn't try to create and save any dependent accounts, but EWS and OWA fail because `verifyLogin` just defaults to calling `login(true);` which tries to create dependent addressbook and calendar accounts, and this fails because the main account hasn't been saved yet. (Presumably under the old code, these accounts would simply be saved, and would linger if you cancelled account setup at the last second.)

Can you please make a PR with a fix?

**Comment by NeilRashbrook** [comment]
I'm used to GitHub auto-linking in both directions automatically (`<user> mentioned this pull request <date>`), but I assume you meant in email too?
